version: "2"
services:
  backend_fpm:
    image: php:7.0.23-fpm-final
    volumes:
      - /usr/share/zoneinfo/PRC:/etc/localtime
      - ${APP_CODE_DIR}:/var/www/html
      - ./conf/php/conf.d:/usr/local/etc/php/conf.d:ro
      - /data/volumes/${COMPOSE_PROJECT_NAME}/backend_fpm/log:/var/log
      - /data/volumes/${COMPOSE_PROJECT_NAME}/backend_fpm/run:/run/php
      - /data/volumes/${COMPOSE_PROJECT_NAME}/backend_fpm/backend/web/assets:/var/www/html/backend/web/assets
      - /data/volumes/${COMPOSE_PROJECT_NAME}/backend_fpm/backend/runtime:/var/www/html/backend/runtime
    restart: always
  backend_nginx:
    image: nginx:1.13.5
    volumes:
      - /usr/share/zoneinfo/PRC:/etc/localtime
      - ${APP_CODE_DIR}:/var/www/html
      - /data/volumes/${COMPOSE_PROJECT_NAME}/backend_fpm/backend/web/assets:/var/www/html/backend/web/assets
      - ./backend_nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /data/volumes/${COMPOSE_PROJECT_NAME}/backend_nginx/log/:/var/log/nginx/
      - ./backend_nginx/docker-entrypoint-patch.sh:/docker-entrypoint-patch.sh
    entrypoint: /docker-entrypoint-patch.sh nginx -g "daemon off;"
    ports:
      - ${BACKEND_WEB_PORT}:80
    restart: always
    links:
      - backend_fpm